### ISSUE TITLE
"Sketchbook" menu only 1 folder deep

### ISSUE THREAD

**Issue by TomW1605** [arduino/arduino-ide#1185]
### Describe the problem

on macos when you got to the sketchbook from the menubar (File>Sketchbook) the menu only goes 1 folder deep. from there everything is compressed in the that folder with no structure to it.

### To reproduce

1. add a sketch to the sketchbook that is 3 folders deep (Arduino>Project>Subproject>Sketch)
2. navegate to the folder in the menubar sketchbook
3. it will show as Sketchbook>Project>Sktech

### Expected behavior

it should show as Sketchbook>Project>Subproject>Sketch

### Arduino IDE version

2.0.0-rc8

### Operating system

macOS

### Operating system version

10.15.7 (19H1519)

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @TomW1605. I'm happy to inform you that this bug is fixed: https://github.com/arduino/arduino-ide/pull/1144

That fix was made after the release of the 2.0.0-rc8 version of the IDE you are using. It is available from the nightly build. The download links are listed here:

https://www.arduino.cc/en/software#nightly-builds

In the future, please make sure to test using the nightly build before submitting an issue in order to verify that it was not already fixed.

**Comment by TomW1605** [comment]
hi, i actualy did test the nighly when i got to the check box but forgot to go back to change the version in the issue

just downloaded version 2.0.0-rc8-nightly-20220713 and the issue still exists.

**Comment by kittaakos** [comment]
I could reproduce it. Thanks for letting us know.

Java IDE:
<img width="480" alt="Screen Shot 2022-07-14 at 15 02 16" src="https://user-images.githubusercontent.com/1405703/178988717-398073d1-8f95-4934-a78f-daf645e584d0.png">


IDE2:
<img width="345" alt="Screen Shot 2022-07-14 at 15 02 25" src="https://user-images.githubusercontent.com/1405703/178988691-55523942-dab7-433f-80de-3923ab7a0ad3.png">

**Comment by TomW1605** [comment]
thanks.
some addiditonal info, if there are more sketches in "Project" they will show up at the same level as the sketches in subfolders.

**Comment by bperrybap** [comment]
This issue still exists in the 2.0 linux release.
IMO, the title of this issue is still a bit vague - at least to me.
i.e. it inst' that the menu only goes 1 directory deep, it is that it hides all the directories from the menu beyond the top level. 


I would add that this issue does not exist in the folder/sketchbook view.
i.e. when you click on the folder icon to get the sketchbook view all the intermediate directories/sub-directories show up properly.
Not sure how these are implemented, but I would think they would be sharing some of the same code to make sure that they are handled the same way.

**Comment by TomW1605** [comment]
i agree the title is a bit vauge but i wouldent say it hides all the directories beyond the top level, that implies that only the sketches in the top folder are shown, when it is actualy just shuving all the sketches to the top. not sure what a better title would be though.

**Comment by bperrybap** [comment]
I agree that getting a title for the issue that is not too long is difficult.
I guess the wording I used might is ambiguous given the readers assumptions.
I was assuming just what it said, it hides all the directories **from the menu**, not that it hides the sketches from the menu.

**Comment by drachezoil** [comment]
Same problem here with 2.0.1 release on windows
displaying:
\sketchbook
---\project1
-----\version1A
-----\version1B
-----\version2A
-----\version2B
instead of:
\sketchbook
---\project1
-----\CodeA
-------\version1A
-------\version2A
-----\CodeB
-------\version1B
-------\version2B

**Comment by craig-james-author** [comment]
This is still not working as of right now (Arduino IDE 2.0.3-nightly-20221227). I have a "test" subdirectory that should appear as a sub-menu. Instead, all of the sketches in the subdirectory are "flattened" into the "sketches" menu. See attached screenshot.
![arduino-sketch-hierarchy-missing](https://user-images.githubusercontent.com/56235518/209736124-0b3561f7-0929-4c21-8429-c0c87230516f.jpg)

**Comment by Papirrruqui** [comment]
Hi to every one. Thanks for resolving the problem... But how do I fix the problem on my PC
